### ISSUE TITLE
Failing to filter correctly with new pyam?

### ISSUE THREAD

**Issue by jkikstra** [GranthamImperial/silicone#117]
**Describe the bug**

After installing `pyam` after its newest refactoring, infilling throws an error when running the climate-assessment despite the input to `infill_all_required_variables` being exactly the same.
It seems that there is some issue in the infilling, seemingly related to not downselecting correctly, especially in the constantratio `filler` function (but potentially a bit higher up).

I tried diving in for a bit but didn't find the issue so I thought it useful to report it here. 

**Failing Test**
I updated `pyam` and `climate-assessment` to their respective master branches.
Then I ran:
```
python scripts/run_pipeline.py tests/test-data/ex2.csv output --num-cfgs 10 --magicc-probabilistic-file data/d57918-drawnset.json
```
with the error log being:
```
INFO:climate_assessment.harmonization_and_infilling:Infilling database: C:\Users\kikstra\Documents\GitHub\climate-assessment\src\climate_assessment\infilling\2020-07-20_ar6_worldemissions_harmonized_2020-08-01.xlsx
WARNING:pyam.core:Filtered IamDataFrame is empty!
['Emissions|HFC|HFC245ca', 'Emissions|BC', 'Emissions|HFC|HFC125', 'Emissions|PFC|CF4', 'Emissions|PFC|C2F6', 'Emissions|PFC|C6F14', 'Emissions|CH4', 'Emissions|CO2', 'Emissions|CO2|Energy and Industrial Processes', 'Emissions|CO', 'Emissions|HFC|HFC134a', 'Emissions|HFC|HFC143a', 'Emissions|HFC|HFC227ea', 'Emissions|HFC|HFC23', 'Emissions|HFC|HFC32', 'Emissions|HFC|HFC43-10', 'Emissions|N2O', 'Emissions|NH3', 'Emissions|NOx', 'Emissions|OC', 'Emissions|SF6', 'Emissions|Sulfur', 'Emissions|VOC']
['Emissions|CO2']
c:\users\kikstra\documents\github\silicone\src\silicone\multiple_infillers\infill_all_required_emissions_for_openscm.py:177: UserWarning: No data for ['Emissions|HFC|HFC245ca'], it will be infilled with 0s
  unavailable_variables
INFO:silicone.database_crunchers.constant_ratio:<class 'silicone.database_crunchers.constant_ratio.ConstantRatio'> won't use any information from the database
Filling required variables:   0%|                                                                                                                                                                    | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scripts/run_pipeline.py", line 9, in <module>
    climate_assessment.cli.pipeline()
  File "C:\Users\kikstra\Miniconda3\envs\test_new_pyam\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\kikstra\Miniconda3\envs\test_new_pyam\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\kikstra\Miniconda3\envs\test_new_pyam\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\kikstra\Miniconda3\envs\test_new_pyam\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\kikstra\documents\github\climate-assessment\src\climate_assessment\cli.py", line 233, in pipeline
    df, key_string, infilling_database, outdir=outdir, do_harmonisation=harmonise
  File "c:\users\kikstra\documents\github\climate-assessment\src\climate_assessment\harmonization_and_infilling.py", line 33, in harmonisation_and_infilling
    database_filepath=infilling_database,
  File "c:\users\kikstra\documents\github\climate-assessment\src\climate_assessment\infilling\__init__.py", line 141, in run_infilling
    check_data_returned=True,
  File "c:\users\kikstra\documents\github\silicone\src\silicone\multiple_infillers\infill_all_required_emissions_for_openscm.py", line 192, in infill_all_required_variables
    **kwarg_dict,
  File "c:\users\kikstra\documents\github\silicone\src\silicone\multiple_infillers\infill_all_required_emissions_for_openscm.py", line 267, in _perform_crunch_and_check
    interpolated = _infill_variable(cruncher, req_var, leaders, to_fill, **kwargs)
  File "c:\users\kikstra\documents\github\silicone\src\silicone\multiple_infillers\infill_all_required_emissions_for_openscm.py", line 357, in _infill_variable
    interpolated = filler(to_fill_var)
  File "c:\users\kikstra\documents\github\silicone\src\silicone\database_crunchers\constant_ratio.py", line 108, in filler
    ), "There are multiple or no units for the lead variable."
AssertionError: There are multiple or no units for the lead variable.
```

**Additional remarks**
Would you @Rlamboll be able to test if you get the same behaviour?

**Comment by Rlamboll** [comment]
Yeah, the newest version of pyam changes how .data works so I expect it breaks a lot of things. I will start looking into this, thanks for reporting it (I didn't realise it had been formally released yet)

**Comment by jkikstra** [comment]
Cheers! 
The data reformatting has just been merged into master, not yet a new release I think.

**Comment by danielhuppmann** [comment]
Thanks for checking @jkikstra!

The pyam-refactoring hasn't been released yet - I was planning to do this later this week unless some serious, unfixable issue is discovered. The behavior of the `data` attribute should work as before.
